//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorksOrderKittable
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectReportDbEntities : DbContext
    {
        public ConnectReportDbEntities()
            : base("name=ConnectReportDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WOKittable_WOClosedLines> WOKittable_WOClosedLines { get; set; }
        public virtual DbSet<WOKittable_WOOpenLines> WOKittable_WOOpenLines { get; set; }
    }
}
