//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorksOrderKittable
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class thas01ReportEntities : DbContext
    {
        public thas01ReportEntities()
            : base("name=thas01ReportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int THAS_CONNECT_PopulateWOKittable_WOClosedLines()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THAS_CONNECT_PopulateWOKittable_WOClosedLines");
        }
    
        public virtual int THAS_CONNECT_PopulateWOKittable_WOOpenLines()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THAS_CONNECT_PopulateWOKittable_WOOpenLines");
        }
    
        public virtual ObjectResult<THAS_CONNECT_WOKittable_GetAllClosedPlannedQuantities_Result> THAS_CONNECT_WOKittable_GetAllClosedPlannedQuantities()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THAS_CONNECT_WOKittable_GetAllClosedPlannedQuantities_Result>("THAS_CONNECT_WOKittable_GetAllClosedPlannedQuantities");
        }
    
        public virtual ObjectResult<THAS_CONNECT_WOKittable_GetAllOpenPlannedQuantities_Result> THAS_CONNECT_WOKittable_GetAllOpenPlannedQuantities()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THAS_CONNECT_WOKittable_GetAllOpenPlannedQuantities_Result>("THAS_CONNECT_WOKittable_GetAllOpenPlannedQuantities");
        }
    
        public virtual ObjectResult<THAS_CONNECT_WOKittable_GoodStock_Result> THAS_CONNECT_WOKittable_GoodStock()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THAS_CONNECT_WOKittable_GoodStock_Result>("THAS_CONNECT_WOKittable_GoodStock");
        }
    }
}
