//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorksOrderKittable
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOKittableResultSet
    {
        public long WOKittable_ID { get; set; }
        public long UID { get; set; }
        public string WONumber { get; set; }
        public string ResponsibilityCode { get; set; }
        public decimal WOTotalPlannedQty { get; set; }
        public decimal TotalPlannedQty { get; set; }
        public decimal TotalActualQty { get; set; }
        public decimal TotalActualKitNeed { get; set; }
        public decimal TotalKittable { get; set; }
        public string CommercialNotes { get; set; }
        public string BatchNotes { get; set; }
        public decimal PartsNotFound { get; set; }
        public decimal OverKitted { get; set; }
        public System.DateTime DateRun { get; set; }
    }
}
